### ISSUE TITLE
[BUG] - longFormat doesn't include separator

### ISSUE THREAD

**Issue by kallewesth** [personnummer/java#113]
`Personnummer.format(true)` doesn't work as described in the javadoc's, separator is omitted if `longFormat==true`

**Comment by Johannestegner** [comment]
Hi and thank you for the report!

The javadocs seems to be wrong, the separator is superfluous in the long format (seeing it's only used to determine if the age is above or below 100, which of course can be seen quite easily in the century in the date).

I will update the documentation asap!
