### ISSUE TITLE
False positives. Not validating the - and + signs

### ISSUE THREAD

**Issue by ullenius** [personnummer/java#15]
The program disregards the `-` and `+` sign in personal numbers (_personnummer_). It is used for determining what century the person was born in. It gets changed from a dash `-` to a plus sign `+` when a person turns 100 years old.

**For example:**
19130401-2931 returns true
19130401+2931 returns true

Only the latter should return true.

References:
[Personnummer och samordningsnummer (Skatteverket)](https://web.archive.org/web/20101122100914/http://www.skatteverket.se/download/18.1e6d5f87115319ffba380001857/70408.pdf) - in Swedish

**Comment by Johannestegner** [comment]
Hi and thank you for the issue report!

Personnummer & Samordningsnummer are YYMMDD+\-XXXX, so if you use the millennial and centurial numbers it's no longer valid.  
Does it give the same result if you use `130401-2931` and `130401+2931`?

Not really sure how we should handle the case though... @frozzare any input?

**Comment by ullenius** [comment]
> Does it give the same result if you use `130401-2931` and `130401+2931`?
> 

Yes. Both return true.

Found some code in another repo by that seems to [address the issue](https://github.com/rolfjod/personnummer-utils/blob/1b2f539965498161f22c4390bc62260ca04ffa7a/src/main/java/se/tqdata/nin/PersonnummerGenerator.java#L133) (uses same licence so it can be used here as well). Haven't tested it though

**Comment by Johannestegner** [comment]
About to put the kids to bed, but will take a look at this after talking to @frozzare about possible solutions asap :)

**Comment by Johannestegner** [comment]
Hi! We have had a long discussion about this now, hehe...
What we have concluded is the following:

As of right now, using 13 characters as input (MCDYMMDD+/-XXXX) is seen as a so called `undefined behaviour` as it is not really a valid social security number.  
We are still discussing how we want it to act in case this is done though, as we would rather see all the packages behave the same way in this kind of instances (discussion in https://github.com/personnummer/meta/issues/18 and soon another issue).  

The good thing though, is that both the numbers will always be equally valid when it comes to the luhn algorithm, as we always remove the millennial and centurial numbers before doing it either way.

The undefined behaviour exists in if the parser chooses the `+/-` or the year when something is passed, that is: 19130401-2931 could either be parsed as 1913 or 2013 (which in validity does not matter either way).

I will close this issue for now and reference it in the nasal demon discussion. :)

**Comment by ullenius** [comment]
I too thought about this for a while. I even wrote som functioning piece of code I ended up throwing away.

And I think you made the right decision. Skatteverket **does not** use the first 4 digits as an indicator of a person's birth date. They use a separate field for this, just look at a Swedish id card. This is because there is a shortage of numbers for certain dates and years.

This class should validate Personal numbers. **Period**. 

I think trying to parse any data out of the `+ -` is `deprecated`. As is parsing birth county ("_län_") and other data that used to be encoded within the personal numbers. The dash or plus sign is a way of formatting output when you have other data at your disposal (birth date in some database). Not a way to determine the validity of the number.
