### ISSUE TITLE
[BUG] - Parse personnummer is broken if you enter an Organisationsnummer

### ISSUE THREAD

**Issue by Rawa** [personnummer/java#39]
**Context**

`Personnummer.parse()` does not throw PersonnummerException if you enter a Organisationnummer.

**Expected outcome**

Get a `PersonnnummerException`
**Actual outcome**

Got a Personnummer object. Only to fail once one calls `toString()`.

**Description**

**Minimal reproducible test case**

        val invalidPin = "556748-7862"
        try {
            val pin = Personnummer.parse(invalidPin)
        } catch (e: Exception) {
            println("We got a error: $e")
        }
        println("Everything is fine")

If you however call toString() on the object you will get a `DateTimeException`

`java.time.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 67`

**Comment by Rawa** [comment]
To clarify, this also means `Personnummer.valid()` is broken as well.
```

    /**
     * Validate a Swedish personal identity number.
     *
     * @param personnummer personal identity number to validate, as string.
     * @return True if valid.
     */
    public static boolean valid(String personnummer) {
        try {
            parse(personnummer);
            return true;
        } catch (PersonnummerException ex) {
            return false;
        }
    }```

**Comment by Johannestegner** [comment]
Thank you for the report! :)

Will take a look at this as soon as possible.
