### ISSUE TITLE
[Q] -  In regards to the Personnummer class line  136 the else statement 

### ISSUE THREAD

**Issue by alanmehio** [personnummer/java#66]
The line  136  has an else and check the day > 60 in case there is no allowance for  coordinatio number as per [SKV spec. ](https://skatteverket.se/privat/internationellt/bosattutomlands/samordningsnummer.4.53a97fe91163dfce2da80001279.html)
`} else if(day > 60) {
            throw new PersonnummerException("Invalid personal identity number.");
        }`

The check is not needed since there will be a check  at line  150 where the day , month and year semantic will be checked from DateTimeFormatter

In Case you want to keep the else statement, it would be nice to check against  day > 31 ( max day in a month )
Not sure why  the day > 60  exist  in the else statement. 
Thanks 
Alan

**Comment by Johannestegner** [comment]
Hi there!
Thanks for the question!

Yes, I guess that it's basically redundant due to the date time check further down.
The reason for 60 is that 61 is where coordination numbers starts:

> Samordningsnummer består liksom personnumret av tio siffror. De inledande sex siffrorna utgår från personens födelsetid med den skillnaden att man lägger till 60 till födelsedagen. För en person som är född den 23 augusti 1964 så blir de sex första siffrorna i samordningsnumret därför 640883.

Will take a look during the day to verify that the check is redundant and remove if it is :)

**Comment by alanmehio** [comment]
Good .

**Comment by Johannestegner** [comment]
Sorry for not responding earlier. 
I've been thinking about this and concluded that I think that the else-clause is warranted. The extra cost of executing the assignments and such instead of just having the else clause makes it worth using.
The 61 vs 31 is not something that I think is a huge issue. We know that coordination numbers start at 61, hence we choose that number instead of 31.

Thank you :)

**Comment by alanmehio** [comment]
Good to hear from you
No worries  it is your project

Cheers
Alan
