### ISSUE TITLE
[BUG] - test numbers not usable

### ISSUE THREAD

**Issue by flyhard** [personnummer/java#70]
**Context**
If we are using test numbers that have a correct checksum but the last 4 digits start with 000 we cannot parse them.

**Expected outcome**
Parsable but some signal available that shows this is not real data

**Actual outcome**
Constructor fails

**Description**

I suggest that parse should work but valid() should fail - and there could be a valid(boolean allowZeros) method that wouldn't fail. 

If this seems like a valid solution, I would be willing to code it.

**Minimal reproducible test case**

Personnummer.parse("187303140003");

**Comment by Johannestegner** [comment]
Hi there.

The idea with parse/constructor is that all actual personnummer objects are actually valid personnummers. Adding special cases for testing is a bit out of scope and would break the API in a way that we don't feel comfortable with.

When it comes to the 3-Zero numbers, is this an official type of test numbers that we have missed? We make use of the "testpersonnummer" data that skatteverket provides from their homepage for all our tests. If it's an official case that we _should_ take a deeper look at and take in to account, please re-open the issue and let me know :)
