### ISSUE TITLE
[FEATURE] - Lombok

### ISSUE THREAD

**Issue by cbhat5** [personnummer/java#85]
**Description**

 Gets rid of boilerplate getters and setters

**Breaking changes**

**Comment by cbhat5** [comment]
@Johannestegner what do you think? (#87 )

**Comment by Johannestegner** [comment]
I'm a bit hesitant to add a new dependency, and seeing the geters and seters in the project are quite few, I find them alright to write (and I'd be a bit scared to expose all private properties by default).

**Comment by cbhat5** [comment]
You could add `@Getter` to each of the private attribute as well for attribute level exposure.  Only the new thing is one would need to install Lombok plugin/extension for their IDE to recognize. And if you want to hide only one of the many attributes, you can put a `@Getter` on top of the class and add the below to that one particular attribute. Really gets rid of lot of boilerplate. If you are still open we can see...

```java

@Getter(AccessLevel.NONE)
@Setter(AccessLevel.NONE)
private int mySecret;

```
